# =============================================================================
# Tempo - Distributed tracing (Cahier Monitoring Technique)
# =============================================================================
# Receiving : Jaeger format, OTLP. Stockage : local backend (S3 pour prod)
# =============================================================================

server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 168h  # 7 days

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: agrilogistic
