#!/bin/bash
# Render Deployment Helper Script
# This script helps configure and deploy to Render

echo "🚀 Render Deployment Helper"
echo ""

# Check if render.yaml exists
if [ ! -f "render.yaml" ]; then
    echo "❌ render.yaml not found in root directory"
    exit 1
fi

echo "✅ render.yaml found"
echo ""
echo "📋 Deployment Steps:"
echo ""
echo "1. Create Render account at https://render.com"
echo "2. Connect your GitHub repository"
echo "3. Create 'Web Service' and select 'Use existing render.yaml'"
echo "4. Configure environment variables:"
echo ""
echo "   Required for agri-api service:"
echo "   - DATABASE_URL (from Neon)"
echo "   - R2_ACCOUNT_ID"
echo "   - R2_ACCESS_KEY_ID"
echo "   - R2_SECRET_ACCESS_KEY"
echo "   - JWT_SECRET (auto-generated by Render)"
echo ""
echo "   Required for agri-ai service:"
echo "   - R2_ACCOUNT_ID"
echo "   - R2_ACCESS_KEY_ID"
echo "   - R2_SECRET_ACCESS_KEY"
echo ""
echo "5. Click 'Create Web Service'"
echo "6. Render will automatically deploy both services"
echo ""
echo "📊 Expected deployment time: ~10 minutes"
echo ""
echo "🔍 Health check endpoints:"
echo "   - API: https://agri-api.onrender.com/health"
echo "   - AI:  https://agri-ai.onrender.com/health"
echo ""
echo "💡 Tip: Use Render's free tier for prototyping"
echo "   - 512MB RAM per service"
echo "   - 750 hours/month (enough for 1 instance)"
echo "   - Auto-sleep after 15 min inactivity"
